services:
  - type: web
    name: kolkata-backend
    runtime: docker
    region: singapore
    plan: starter
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 1
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQL_HOST
        value: zephyr.proxy.rlwy.net
      - key: MYSQL_PORT
        value: "31887"
      - key: MYSQL_DATABASE
        value: railway
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://sidhhi-vinayak-frontend.onrender.com
      - key: APP_URL
        value: https://sidhhi-vinayak-backend.onrender.com/api
      - key: UPLOAD_DIR
        value: /opt/render/project/uploads
